# Generated by Django 4.1 on 2022-08-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_sum', models.FloatField()),
                ('all_quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ImageField(upload_to='img/client/')),
                ('name', models.CharField(max_length=255)),
                ('car_number', models.CharField(max_length=8)),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('bonus', models.IntegerField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='dashboard.client')),
            ],
        ),
    ]
