# Generated by Django 4.1 on 2022-08-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='card_id',
            field=models.ImageField(blank=True, null=True, upload_to='img/client/'),
        ),
    ]
